apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrosolutions-identidade
  labels:
    app: agrosolutions-identidade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrosolutions-identidade
  template:
    metadata:
      labels:
        app: agrosolutions-identidade
    spec:
      containers:
      - name: agrosolutions-identidade
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: agrosolutions-identidade-secret
