apiVersion: v1
kind: Service
metadata:
  name: agrosolutions-identidade
spec:
  type: LoadBalancer
  selector:
    app: agrosolutions-identidade
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
